# Generated by Django 4.0.4 on 2022-05-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('release_date', models.CharField(default='', max_length=10)),
                ('director', models.CharField(default='', max_length=100)),
                ('imdb_rating', models.IntegerField(default=0)),
                ('run_time', models.IntegerField(default=0)),
                ('production_company', models.CharField(default='', max_length=500)),
                ('language', models.CharField(default='', max_length=50)),
                ('image_url', models.CharField(default='', max_length=350)),
                ('overview', models.CharField(default='', max_length=2048)),
                ('released', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'movie_db',
            },
        ),
    ]
