# Generated by Django 4.0.4 on 2022-05-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('recommandation_percent', models.IntegerField(default=0)),
                ('image_url', models.CharField(default='', max_length=250)),
            ],
            options={
                'db_table': 'MOVIES',
            },
        ),
    ]
